# =============================================================================
# CHECKOV IAC SCAN JOB
# =============================================================================
#
# Repository: https://github.com/bridgecrewio/checkov
#
# TO USE THIS JOB:
# 1. Copy this entire job definition into .github/workflows/06-iac-scan.yml
# 2. Place it under the "jobs:" section
# 3. The job will automatically scan all terraform files in infra/
# =============================================================================

pipeline-scan-checkov:
  name: Analyze Github Workflows with Checkov
  runs-on: ubuntu-latest
  steps:
    # Checkout the repository with full history
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Run Checkov on all workflow files
    - name: Checkov Scan
      uses: bridgecrewio/checkov-action@v12.2776.0
      with:
        directory: infra/
        framework: terraform