name: Pipeline Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  pipeline-scan:
    name: Analyze Github Workflows
    runs-on: ubuntu-latest
    steps:
      - name: to_remove
        id: to_remove
        run: |
          echo "Copy here the workflow of the pipeline scan tool you want to use.
          Inside workshop/pipeline_scan/{tool}/workflow.yml"
