name: Code Security Analysis

on:
  workflow_call:
    outputs:
      sca-result:
        description: "SCA scan result"
        value: ${{ jobs.dependency_check.outputs.result }}

jobs:
  sca-scan:
    name: SCA Scan
    runs-on: ubuntu-latest
    steps:
      - name: to_remove
        id: to_remove
        run: |
          echo "Copy here the workflow of the SCA scan tool you want to use.
          Inside workshop/code_scan/{tool}/workflow.yml"
