name: Code Security Analysis

on:
  workflow_call:
    outputs:
      sca-result:
        description: "SCA scan result"
        value: ${{ jobs.dependency_check.outputs.result }}

jobs:
  dependency_check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML,JSON'
          failOnCVSS: 7
          out: 'reports'

      - name: Upload Dependency-Check HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report-html
          path: reports/dependency-check-report.html

      - name: Upload Dependency-Check JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report-json
          path: reports/dependency-check-report.json

      - name: Set SCA Result Output
        id: set-result
        run: echo "result=success" >> $GITHUB_OUTPUT
