name: Secrets Detection

on:
  workflow_call:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  secrets-scan:
    name: Secrets Detection Scan
    runs-on: ubuntu-latest
    steps:
      - name: to_remove
        id: to_remove
        run: |
          echo "Copy here the workflow of the secrets scan tool you want to use.
          Inside workshop/secrets_scan/{tool}/workflow.yml"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@6641d4ba5b684fffe195b9820345de1bf19f3181 # v3.89.2
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified
