name: Secrets Scan 

on:
  workflow_call:
    outputs:
      secrets-result:
        description: "Secrets scan result"
        value: ${{ jobs.secrets-scan.outputs.result }}

jobs:
  # 🚧 REPLACE THIS ENTIRE 'jobs:' SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/secrets_scan/{tool}/workflow.yml
  
  workshop-placeholder:
    name: "🚧 Workshop Exercise Placeholder"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.placeholder.outputs.result }}
    steps:
      - name: Placeholder
        id: placeholder
        run: |
          echo "Replace this job with content from workshop folder!"
          echo "result=workshop-placeholder" >> $GITHUB_OUTPUT