name: Secrets Detection

on:
  workflow_call:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  secrets-scan:
    name: Secrets Detection Scan
    runs-on: ubuntu-latest
    steps:
      - name: to_remove
        id: to_remove
        run: |
          echo "Copy here the workflow of the secrets scan tool you want to use.
          Inside workshop/secrets_scan/{tool}/workflow.yml"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        run: |
          # Install TruffleHog
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

          # Run filesystem scan - will fail if secrets found
          trufflehog filesystem . --no-verification --filter-entropy=1.0 --results="verified,unknown,unverified,filtered_unverified" --fail
