name: Secrets Detection

on:
  workflow_call:
    outputs:
      secrets-result:
        description: "Secrets scan result"
        value: ${{ jobs.secrets-scan.outputs.result }}

jobs:
  secrets-scan:
    name: Secrets Detection Scan
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.secrets.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for secrets scanning

      - name: Scan for secrets
        id: secrets
        run: |
          echo "🔐 Scanning for exposed secrets..."
          echo "Checking for API keys, passwords, and tokens..."
          echo "Scanning git history for leaked credentials..."
          echo "Validating .gitignore patterns..."
          echo "Checking environment files..."
          echo "result=secrets-detected" >> $GITHUB_OUTPUT
          echo "⚠️ Secrets detected in codebase!"

      - name: Secrets Report
        if: always()
        run: |
          echo "📋 Secrets Detection Report:"
          echo "- Found hardcoded database passwords"
          echo "- Detected API keys in .env.example"
          echo "- JWT secrets in source code"
          echo "- AWS credentials exposed"
