name: Secrets Detection

on:
  workflow_call:
    outputs:
      secrets-result:
        description: "Secrets scan result"
        value: ${{ jobs.secrets-scan.outputs.result }}

jobs:
  secrets-scan:
    name: Secrets Detection Scan
    runs-on: ubuntu-latest
    steps:
      - name: to_remove
        id: to_remove
        run: |
          echo "Copy here the workflow of the secrets scan tool you want to use.
          Inside workshop/secrets_scan/{tool}/workflow.yml"