name: Build Application

on:
  workflow_call:
    outputs:
      image-digest:
        description: "Built image digest"
        value: ${{ jobs.build.outputs.digest }}
      image-tag:
        description: "Built image tag"
        value: ${{ jobs.build.outputs.tag }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.imageid }}
      tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./code
          platforms: linux/amd64
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Summary
        run: |
          echo "📦 Build Summary:"
          echo "- Image built successfully: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "- Tags: ${{ steps.meta.outputs.tags }}"
          echo "- Image ID: ${{ steps.build.outputs.imageid }}"
          echo "✅ Build completed - Image ready for deployment"
