name: Build Application

on:
  workflow_call:
    outputs:
      image-digest:
        description: "Built image digest"
        value: ${{ jobs.build.outputs.digest }}
      image-tag:
        description: "Built image tag"
        value: ${{ jobs.build.outputs.tag }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      tag: ${{ steps.build.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-

      - name: Build Docker image
        id: build
        run: |
          echo "🏗️ Building Docker image..."
          echo "Compiling application..."
          echo "Creating container image..."
          echo "✅ Build completed successfully"

      - name: Build Summary
        run: |
          echo "📦 Build Summary:"
          echo "- Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
