name: Container Security Scan

on:
  workflow_call:
    inputs:
      image-digest:
        description: "Container image digest to scan"
        required: true
        type: string
    outputs:
      scan-result:
        description: "Container scan result"
        value: ${{ jobs.container-scan.outputs.result }}

jobs:
  container-scan:
    name: Container Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: to_remove
        id: to_remove
        run: |
          echo "Copy here the workflow of the container scan tool you want to use.
          Inside workshop/container_scan/{tool}/workflow.yml"