name: Container Security Scan

on:
  workflow_call:
    inputs:
      image-digest:
        description: "Container image digest to scan"
        required: true
        type: string
    outputs:
      scan-result:
        description: "Container scan result"
        value: ${{ jobs.container-scan.outputs.result }}

jobs:
  # 🚧 REPLACE THIS ENTIRE 'jobs:' SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/container_scan/{tool}/workflow.yml
  
  workshop-placeholder:
    name: "🚧 Workshop Exercise Placeholder"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.placeholder.outputs.result }}
    steps:
      - name: Placeholder
        id: placeholder
        run: |
          echo "Replace this job with content from workshop folder!"
          echo "result=workshop-placeholder" >> $GITHUB_OUTPUT