name: Infrastructure Security Scan

on:
  workflow_call:
    outputs:
      iac-result:
        description: "IaC scan result"
        value: ${{ jobs.iac-scan.outputs.result }}

jobs:
  iac-scan:
    name: Infrastructure Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: to_remove
        id: to_remove
        run: |
          echo "Copy here the workflow of the IaC scan tool you want to use.
          Inside workshop/iac_scan/{tool}/workflow.yml"