name: Infrastructure Security Scan

on:
  workflow_call:
    outputs:
      iac-result:
        description: "IaC scan result"
        value: ${{ jobs.iac-scan.outputs.result }}

jobs:
  pipeline-scan-checkov:
    name: Analyze Github Workflows with Checkov
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with full history
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run Checkov on all workflow files
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12.2776.0
        with:
          directory: infra/
          framework: terraform
