name: Runtime Security Testing

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        type: string
      app-url:
        description: "Application URL to test"
        required: true
        type: string
    outputs:
      dast-result:
        description: "DAST scan result"
        value: ${{ jobs.dast.outputs.result }}
      load-test-result:
        description: "Load test result"
        value: ${{ jobs.load-test.outputs.result }}

jobs:
  # 🚧 REPLACE THIS ENTIRE 'jobs:' SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/{scan-type}/workflow.yml
  
  workshop-placeholder:
    name: "🚧 Workshop Exercise Placeholder"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.placeholder.outputs.result }}
    steps:
      - name: Placeholder
        id: placeholder
        run: |
          echo "Replace this job with content from workshop folder!"
          echo "result=workshop-placeholder" >> $GITHUB_OUTPUT