name: Build and Scan Application

on:
  workflow_call:
    outputs:
      image-digest:
        description: "Built image digest"
        value: ${{ jobs.build-and-container-scan.outputs.digest }}
      image-tag:
        description: "Built image tag"
        value: ${{ jobs.build-and-container-scan.outputs.tag }}
      scan-result:
        description: "Container scan result"
        value: ${{ jobs.build-and-container-scan.outputs.scan-result }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # 🚧 REPLACE THIS ENTIRE 'jobs:' SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/container_scan/{tool}/workflow.yml

  build-and-container-scan:
    name: "🚧 Build and Container Scan - Workshop Placeholder"
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.placeholder.outputs.digest }}
      tag: ${{ steps.placeholder.outputs.tag }}
      scan-result: ${{ steps.placeholder.outputs.scan-result }}
    steps:
      - name: Workshop Placeholder
        id: placeholder
        run: |
          echo "🚧 Replace this job with content from workshop/container_scan/{tool}/workflow.yml!"
          echo "This will implement: Build → Container Scan → Push workflow with your chosen tool"
          echo "digest=workshop-placeholder" >> $GITHUB_OUTPUT
          echo "tag=workshop-placeholder" >> $GITHUB_OUTPUT
          echo "scan-result=workshop-placeholder" >> $GITHUB_OUTPUT