name: Code Security Analysis

on:
  workflow_call:
    outputs:
      scan-result:
        description: "Code scan result"
        value: ${{ jobs.code-scan.outputs.result }}

jobs:
  # 🚧 REPLACE THIS ENTIRE 'jobs:' SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/code_scan/{tool}/workflow.yml
  
  code-scan:
    name: "🚧 Code Scan - Workshop Placeholder"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.placeholder.outputs.result }}
    steps:
      - name: Workshop Placeholder
        id: placeholder
        run: |
          echo "🚧 Replace this job with content from workshop/code_scan/{tool}/workflow.yml!"
          echo "This will implement: Code security analysis with your chosen tool"
          echo "result=workshop-placeholder" >> $GITHUB_OUTPUT