name: Pipeline Orchestrator

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  pipeline-scan:
    uses: ./.github/workflows/pipeline-scan.yml
    secrets: inherit

  code-scan:
    needs: pipeline-scan
    uses: ./.github/workflows/code-scan.yml

  secrets-scan:
    needs: pipeline-scan
    uses: ./.github/workflows/secrets-scan.yml
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

  iac-scan:
    needs: pipeline-scan
    uses: ./.github/workflows/iac-scan.yml

  build-and-container-scan:
    needs: [code-scan, secrets-scan]
    uses: ./.github/workflows/build-and-container-scan.yml

  deploy-infrastructure:
    needs: iac-scan
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-infrastructure.yml

  deploy-application:
    needs: [build-and-container-scan, deploy-infrastructure]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-application.yml

  runtime-infra-scan:
    needs: deploy-application
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/runtime-infra-scan.yml
    with:
      environment: staging
      app-url: https://workshop-app-staging.example.com

  dast:
    needs: deploy-application
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/dast.yml
    with:
      environment: staging
      app-url: https://workshop-app-staging.example.com

  integration-test:
    needs: deploy-application
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/integration-test.yml
    with:
      environment: staging
      app-url: https://workshop-app-staging.example.com

  pipeline-summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs:
      [
        pipeline-scan,
        code-scan,
        secrets-scan,
        iac-scan,
        build-and-container-scan,
      ]
    if: always()
    steps:
      - name: Pipeline Results Summary
        run: |
          echo "🎯 Perfect Pipeline Workshop - Results Summary"
          echo "============================================"
          echo "Pipeline Scan: ${{ needs.pipeline-scan.outputs.scan-result }}"
          echo "Code Scan: ${{ needs.code-scan.outputs.scan-result }}"
          echo "Secrets Scan: ${{ needs.secrets-scan.outputs.scan-result }}"
          echo "IaC Scan: ${{ needs.iac-scan.outputs.scan-result }}"
          echo "Container Scan: ${{ needs.build-and-container-scan.outputs.scan-result }}"
          echo "============================================"
          echo "🎓 Workshop completed! Review the security findings above."
