name: Pipeline Security Scan

on:
  workflow_call:
    outputs:
      scan-result:
        description: "Pipeline scan result"
        value: ${{ jobs.pipeline-scan.outputs.result }}

jobs:
  checkout-leak:
    name: "actions/checkout can leak GitHub credentials"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show `.git/config` content
        run: |
          cat .git/config