name: Pipeline Security Scan

on:
  workflow_call:
    outputs:
      scan-result:
        description: "Pipeline scan result"
        value: ${{ jobs.pipeline-scan.outputs.result }}

jobs:
  runtime-infra-scan:
    name: Runtime Infrastructure Scan with Prowler
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scan-result.outputs.result }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
            role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
            role-session-name: ProwlerSession
            aws-region: ${{ vars.AWS_REGION }}
            role-duration-seconds: ${{ vars.AWS_IAM_ROLE_SESSION_DURATION }}

      - name: Install Prowler
        run: |
            pipx install prowler
            prowler -v

      - name: Run Prowler
        id: prowler
        run: |
            prowler aws --service iam s3
        continue-on-error: true

      - name: Message
        run: |
            echo "Prowler run completed"

      - name: Set scan result
        id: scan-result
        if: always()
        run: |
          if [ "${{ steps.prowler.outcome }}" == "success" ]; then
            echo "result=success" >> "$GITHUB_OUTPUT"
            echo "✅ Pipeline scan passed"
          else
            echo "result=failure" >> "$GITHUB_OUTPUT"
            echo "❌ Pipeline scan failed"
          fi
