name: Pipeline Orchestrator

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  pipeline-scan:
    uses: ./.github/workflows/pipeline-scan.yml

  code-analysis:
    needs: pipeline-scan
    uses: ./.github/workflows/code-analysis.yml

  secrets-scan:
    needs: pipeline-scan
    uses: ./.github/workflows/secrets-scan.yml
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

  iac-scan:
    needs: pipeline-scan
    uses: ./.github/workflows/iac-scan.yml

  build:
    needs: [code-analysis, secrets-scan]
    uses: ./.github/workflows/build.yml

  deploy-infrastructure:
    needs: iac-scan
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      environment: staging

  deploy-application:
    needs: [build, deploy-infrastructure]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: staging
      image-digest: ${{ needs.build.outputs.image-digest }}

  runtime-infra-scan:
    needs: deploy-application
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/runtime-infra-scan.yml
    with:
      environment: staging
      app-url: https://workshop-app-staging.example.com

  pipeline-summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs:
      [
        pipeline-scan,
        code-analysis,
        secrets-scan,
        iac-scan,
        build,
      ]
    if: always()
    steps:
      - name: Pipeline Results Summary
        run: |
          echo "🎯 Perfect Pipeline Workshop - Results Summary"
          echo "============================================"
          echo "Pipeline Scan: ${{ needs.pipeline-scan.outputs.scan-result }}"
          echo "SAST: ${{ needs.code-analysis.outputs.sast-result }}"
          echo "SCA: ${{ needs.code-analysis.outputs.sca-result }}"
          echo "Secrets: ${{ needs.secrets-scan.outputs.secrets-result }}"
          echo "IaC Scan: ${{ needs.iac-scan.outputs.iac-result }}"
          echo "Build & Container Scan: ${{ needs.build.outputs.scan-result }}"
          echo "============================================"
          echo "🎓 Workshop completed! Review the security findings above."
