name: Runtime Security Testing

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        type: string
      app-url:
        description: "Application URL to test"
        required: true
        type: string
    outputs:
      dast-result:
        description: "DAST scan result"
        value: ${{ jobs.dast.outputs.result }}
      load-test-result:
        description: "Load test result"
        value: ${{ jobs.load-test.outputs.result }}

jobs:
  iac-scan:
    name: "🚧 Workshop Placeholder"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.placeholder.outputs.result }}
    steps:
      - name: Workshop Placeholder
        id: placeholder
        run: |
          echo "🚧 Replace this job with content from workshop/iac_scan/{tool}/workflow.yml!"
          echo "This will implement: Infrastructure security scan with your chosen tool"
          echo "result=workshop-placeholder" >> "$GITHUB_OUTPUT"